# Generated by Django 3.2.4 on 2023-05-01 11:34

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Last Name')),
                ('type', models.CharField(blank=True, choices=[('poster', 'poster'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='poster', max_length=10, null=True)),
                ('paypal', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Paypal Email')),
                ('bank_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bank Name')),
                ('account_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Account Number')),
                ('account_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Account Name')),
                ('referrer', models.CharField(blank=True, max_length=60, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-created',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
