# Generated by Django 3.2.4 on 2023-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, choices=[('Poster', 'Poster'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Poster', max_length=10, null=True),
        ),
    ]
