# Generated by Django 3.2.4 on 2023-05-01 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20230501_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='advert',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='adverts_lovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advert',
            name='loves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advert',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='adverts_viewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advert',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
