# Generated by Django 3.2.4 on 2023-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230501_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='alt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
