# Generated by Django 3.2.4 on 2023-05-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_advert_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='edits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='advert',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
