# Generated by Django 3.2.4 on 2023-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230502_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under review', 'Under review')], default='Under review', max_length=12, null=True),
        ),
    ]
