# Generated by Django 3.2.4 on 2023-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_advert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique_for_date='created'),
        ),
    ]
