# Generated by Django 3.2.4 on 2023-05-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_advert_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='post',
            new_name='article',
        ),
    ]
